<?php

namespace Cooler\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * beersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class beersRepository extends EntityRepository
{
}
